const countries = {
  "am-ET": "Amharic (Ethiopia)",
  "ar-AE": "Arabic (United Arab Emirates)",
  "ar-BH": "Arabic (Bahrain)",
  "be-BY": "Belarusian (Belarus)",
  "bi-VU": "Bislama (Vanuatu)",
  "de-DE": "German (Germany)",
  "de-AT": "German (Austria)",
  "de-CH": "German (Switzerland)",
  "en-AU": "English (Australia)",
  "en-GB": "English (United Kingdom)",
  "en-US": "English (United States)",
  "en-CA": "English (Canada)",
  "es-ES": "Spanish (Spain)",
  "es-MX": "Spanish (Mexico)",
  "pt-BR": "Portuguese (Brazil)",
  "pt-PT": "Portuguese (Portugal)",
  "fr-FR": "French (France)",
  "fr-CA": "French (Canada)",
  "ru-RU": "Russian (Russia)",
  "zh-CN": "Chinese (Simplified, China)",
  "zh-TW": "Chinese (Traditional, Taiwan)",
  "ja-JP": "Japanese (Japan)",
  "ko-KR": "Korean (South Korea)",
  "ar-SA": "Arabic (Saudi Arabia)",
  "hi-IN": "Hindi (India)",
  "it-IT": "Italian (Italy)",
  "nl-NL": "Dutch (Netherlands)",
  "sv-SE": "Swedish (Sweden)",
  "no-NO": "Norwegian (Norway)",
  "da-DK": "Danish (Denmark)",
  "fi-FI": "Finnish (Finland)",
  "pl-PL": "Polish (Poland)",
  "tr-TR": "Turkish (Turkey)",
  "vi-VN": "Vietnamese (Vietnam)",
  "th-TH": "Thai (Thailand)",
  "id-ID": "Indonesian (Indonesia)",
  "ms-MY": "Malay (Malaysia)",
  "he-IL": "Hebrew (Israel)",
  "el-GR": "Greek (Greece)",
  "ro-RO": "Romanian (Romania)",
  "hu-HU": "Hungarian (Hungary)",
  "uk-UA": "Ukrainian (Ukraine)",
  "bg-BG": "Bulgarian (Bulgaria)",
  "sr-RS": "Serbian (Serbia)",
  "sk-SK": "Slovak (Slovakia)",
  "sl-SI": "Slovenian (Slovenia)",
  "hr-HR": "Croatian (Croatia)",
  "lt-LT": "Lithuanian (Lithuania)",
  "lv-LV": "Latvian (Latvia)",
  "et-EE": "Estonian (Estonia)",
  "ca-ES": "Catalan (Spain)",
  "eu-ES": "Basque (Spain)",
};

const languages = {
  en: "English",
  es: "Spanish",
  fr: "French",
  de: "German",
  pt: "Portuguese",
  ru: "Russian",
  zh: "Chinese",
  ja: "Japanese",
  ko: "Korean",
  ar: "Arabic",
  hi: "Hindi",
  it: "Italian",
  nl: "Dutch",
  sv: "Swedish",
  no: "Norwegian",
  da: "Danish",
  fi: "Finnish",
  pl: "Polish",
  cs: "Czech",
  tr: "Turkish",
  vi: "Vietnamese",
  th: "Thai",
  id: "Indonesian",
  ms: "Malay",
  he: "Hebrew",
  el: "Greek",
  ro: "Romanian",
  hu: "Hungarian",
  uk: "Ukrainian",
  bg: "Bulgarian",
  sr: "Serbian",
  sk: "Slovak",
  sl: "Slovenian",
  hr: "Croatian",
  lt: "Lithuanian",
  lv: "Latvian",
  et: "Estonian",
  ca: "Catalan",
  eu: "Basque",
  am: "Amharic",
  bi: "Bislama",
};

const countryCodes = {
  US: "United States",
  GB: "United Kingdom",
  CA: "Canada",
  MX: "Mexico",
  BR: "Brazil",
  PT: "Portugal",
  ES: "Spain",
  FR: "France",
  DE: "Germany",
  IT: "Italy",
  RU: "Russia",
  CN: "China",
  TW: "Taiwan",
  JP: "Japan",
  KR: "South Korea",
  IN: "India",
  AU: "Australia",
  NZ: "New Zealand",
  SA: "Saudi Arabia",
  AE: "United Arab Emirates",
  EG: "Egypt",
  TR: "Turkey",
  NL: "Netherlands",
  SE: "Sweden",
  NO: "Norway",
  DK: "Denmark",
  FI: "Finland",
  PL: "Poland",
  BE: "Belgium",
  CH: "Switzerland",
  AR: "Argentina",
  PK: "Pakistan",
  IL: "Israel",
  VN: "Vietnam",
  TH: "Thailand",
  ID: "Indonesia",
  MY: "Malaysia",
  NG: "Nigeria",
  PH: "Philippines",
  ZA: "South Africa",
  CZ: "Czech Republic",
  GR: "Greece",
  RO: "Romania",
  HU: "Hungary",
  UA: "Ukraine",
  BG: "Bulgaria",
};

export { countries, languages, countryCodes };
